google:
  # файл должен лежать в корне проекта, как его получить и настроить аккаунт -
  #  см. https://habr.com/ru/post/483302/
  credentials_file: credentials.json
  # это scope, который мы указали при настройке аккаунта google,
  #  должно хватить spreadsheets.readonly
  scopes:
    - scope: "https://www.googleapis.com/auth/spreadsheets.readonly"
spreadsheet:
  # идентификатор документа google
  id: "google-doc-id"
  # какую область документа экспортировать - здесь стоит указать название листа
  range: "Лист1"
export:
  # какая папка должна создаваться для csv файла
  secret_url_part: "secret_dir"
  # название csv файла
  csv_file_name: students.csv
